import { createSlice } from "@reduxjs/toolkit";
import { signInThunk, signUpThunk } from "./authThunk";

// Define the type of the authentication state
export interface AuthState {
  isAuthorized: boolean;
  userDetails: any;
  JWT: string | null;
  status: "idle" | "loading" | "failed" | "success" | "checkedAuth";
}

// Initial state for the authentication slice
const initialState: AuthState = {
  isAuthorized: false,
  userDetails: null,
  JWT: null,
  status: "idle",
};

// Create the authentication slice using Redux Toolkit
export const authSlice = createSlice({
  name: "auth",
  initialState,
  reducers: {
    // Action to set JWT and store it in local storage
    setJWT: (state, action) => {
      localStorage.setItem("token", action.payload);
      state.JWT = action.payload;
    },
    // Action to set user data from decoded JWT
    setUserData: (state) => {
      const { JWT } = state;
      if (JWT) {
        const encodedUserData = JWT.split(".")[1];
        state.userDetails = JSON.parse(atob(encodedUserData));
        state.isAuthorized = true;
      }
    },
    // Action to retrieve JWT from local storage
    getJWTFromStorage: (state) => {
      const token = localStorage.getItem("token");
      state.JWT = token;
    },
    // Action to set the status of authentication
    setStatus: (state, action) => {
      state.status = action.payload;
    },
    // Action to log out and clear authentication state
    logOut: (state) => {
      localStorage.removeItem("token");
      state.isAuthorized = false;
      state.userDetails = null;
      state.JWT = null;
    },
  },
  // Extra reducers to handle asynchronous actions using thunks
  extraReducers: (builder) => {
    builder
      // Reducer for sign-in thunk in the loading state
      .addCase(signInThunk.pending, (state) => {
        state.status = "loading";
      })
      // Reducer for sign-in thunk based on fulfillment
      .addCase(signInThunk.fulfilled, (state, action) => {
        state.status = action.payload.token ? "success" : "failed";
      })
      // Reducer for sign-up thunk in the loading state
      .addCase(signUpThunk.pending, (state) => {
        state.status = "loading";
      })
      // Reducer for sign-up thunk based on fulfillment
      .addCase(signUpThunk.fulfilled, (state, action) => {
        state.status = action.payload.token ? "success" : "failed";
      });
  },
});

// Export individual actions from the authentication slice
export const { setJWT, setUserData, getJWTFromStorage, setStatus, logOut } =
  authSlice.actions;

// Export the reducer function generated by createSlice
export default authSlice.reducer;
