// Import createSlice from Redux Toolkit for creating a slice of the Redux store
import { createSlice } from "@reduxjs/toolkit";

// Create a Redux slice for navigation state
export const navSlice = createSlice({
  // Name of the slice, useful for organization and debugging
  name: "nav",
  
  // Initial state for the navigation slice
  initialState: {
    currentSection: 3, //Default
    currentSubSection: 1, 
  },

  // Reducers define how the state can be mutated
  reducers: {
    // Action to set the current section in the navigation state
    setSection: (state, action) => {
      state.currentSection = action.payload;
    },
    // Action to set the current subsection in the navigation state
    setSubSection: (state, action) => {
      state.currentSubSection = action.payload;
    },
  },
});

// Export individual actions from the navigation slice
export const { setSection, setSubSection } = navSlice.actions;

// Export the reducer function generated by createSlice
export default navSlice.reducer;
